name: capstone_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  image_picker: ^1.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  assets:
   - assets/logo/
   - assets/image/
  fonts:
    - family: Klavika
      fonts:
        - asset: assets/fonts/KlavikaBoldBold.otf
    - family: Frutiger
      fonts:
        - asset: assets/fonts/FrutigerLTStd-Roman.otf

  uses-material-design: true